// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.1 (64-bit)
// Version: 2022.1.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_ap_fixed_16_8_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
input  [15:0] p_read29;
input  [15:0] p_read30;
input  [15:0] p_read31;
input  [15:0] p_read32;
input  [15:0] p_read33;
input  [15:0] p_read34;
input  [15:0] p_read35;
input  [15:0] p_read36;
input  [15:0] p_read37;
input  [15:0] p_read38;
input  [15:0] p_read39;
input  [15:0] p_read40;
input  [15:0] p_read41;
input  [15:0] p_read42;
input  [15:0] p_read43;
input  [15:0] p_read44;
input  [15:0] p_read45;
input  [15:0] p_read46;
input  [15:0] p_read47;
input  [15:0] p_read48;
input  [15:0] p_read49;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
output  [13:0] ap_return_8;
output  [13:0] ap_return_9;

reg ap_idle;
reg[13:0] ap_return_0;
reg[13:0] ap_return_1;
reg[13:0] ap_return_2;
reg[13:0] ap_return_3;
reg[13:0] ap_return_4;
reg[13:0] ap_return_5;
reg[13:0] ap_return_6;
reg[13:0] ap_return_7;
reg[13:0] ap_return_8;
reg[13:0] ap_return_9;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln151_fu_2764_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] outidx_address0;
reg    outidx_ce0;
wire   [3:0] outidx_q0;
wire   [8:0] w5_V_address0;
reg    w5_V_ce0;
wire   [9:0] w5_V_q0;
reg   [0:0] do_init_reg_524;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] in_index22_reg_1189;
reg   [8:0] w_index21_reg_1203;
reg   [15:0] p_read50_phi_reg_1216;
reg   [15:0] p_read151_phi_reg_1229;
reg   [15:0] p_read252_phi_reg_1242;
reg   [15:0] p_read353_phi_reg_1255;
reg   [15:0] p_read454_phi_reg_1268;
reg   [15:0] p_read555_phi_reg_1281;
reg   [15:0] p_read656_phi_reg_1294;
reg   [15:0] p_read757_phi_reg_1307;
reg   [15:0] p_read858_phi_reg_1320;
reg   [15:0] p_read959_phi_reg_1333;
reg   [15:0] p_read1060_phi_reg_1346;
reg   [15:0] p_read1161_phi_reg_1359;
reg   [15:0] p_read1262_phi_reg_1372;
reg   [15:0] p_read1363_phi_reg_1385;
reg   [15:0] p_read1464_phi_reg_1398;
reg   [15:0] p_read1565_phi_reg_1411;
reg   [15:0] p_read1666_phi_reg_1424;
reg   [15:0] p_read1767_phi_reg_1437;
reg   [15:0] p_read1868_phi_reg_1450;
reg   [15:0] p_read1969_phi_reg_1463;
reg   [15:0] p_read2070_phi_reg_1476;
reg   [15:0] p_read2171_phi_reg_1489;
reg   [15:0] p_read2272_phi_reg_1502;
reg   [15:0] p_read2373_phi_reg_1515;
reg   [15:0] p_read2474_phi_reg_1528;
reg   [15:0] p_read2575_phi_reg_1541;
reg   [15:0] p_read2676_phi_reg_1554;
reg   [15:0] p_read2777_phi_reg_1567;
reg   [15:0] p_read2878_phi_reg_1580;
reg   [15:0] p_read2979_phi_reg_1593;
reg   [15:0] p_read3080_phi_reg_1606;
reg   [15:0] p_read3181_phi_reg_1619;
reg   [15:0] p_read3282_phi_reg_1632;
reg   [15:0] p_read3383_phi_reg_1645;
reg   [15:0] p_read3484_phi_reg_1658;
reg   [15:0] p_read3585_phi_reg_1671;
reg   [15:0] p_read3686_phi_reg_1684;
reg   [15:0] p_read3787_phi_reg_1697;
reg   [15:0] p_read3888_phi_reg_1710;
reg   [15:0] p_read3989_phi_reg_1723;
reg   [15:0] p_read4090_phi_reg_1736;
reg   [15:0] p_read4191_phi_reg_1749;
reg   [15:0] p_read4292_phi_reg_1762;
reg   [15:0] p_read4393_phi_reg_1775;
reg   [15:0] p_read4494_phi_reg_1788;
reg   [15:0] p_read4595_phi_reg_1801;
reg   [15:0] p_read4696_phi_reg_1814;
reg   [15:0] p_read4797_phi_reg_1827;
reg   [15:0] p_read4898_phi_reg_1840;
reg   [15:0] p_read4999_phi_reg_1853;
reg   [15:0] acc_V20_reg_1866;
reg   [15:0] acc_V_118_reg_1880;
reg   [15:0] acc_V_216_reg_1894;
reg   [15:0] acc_V_314_reg_1908;
reg   [15:0] acc_V_412_reg_1922;
reg   [15:0] acc_V_510_reg_1936;
reg   [15:0] acc_V_68_reg_1950;
reg   [15:0] acc_V_76_reg_1964;
reg   [15:0] acc_V_84_reg_1978;
reg   [15:0] acc_V_92_reg_1992;
wire   [8:0] w_index_fu_2752_p2;
reg   [8:0] w_index_reg_3145;
wire   [31:0] in_index_1_fu_2758_p2;
reg   [31:0] in_index_1_reg_3150;
reg   [0:0] icmp_ln151_reg_3156;
reg   [0:0] icmp_ln151_reg_3156_pp0_iter1_reg;
reg   [0:0] icmp_ln151_reg_3156_pp0_iter2_reg;
reg   [0:0] icmp_ln151_reg_3156_pp0_iter3_reg;
reg   [0:0] icmp_ln151_reg_3156_pp0_iter4_reg;
reg   [3:0] out_index_reg_3160;
reg   [3:0] out_index_reg_3160_pp0_iter2_reg;
reg   [3:0] out_index_reg_3160_pp0_iter3_reg;
reg   [3:0] out_index_reg_3160_pp0_iter4_reg;
wire   [15:0] a_V_fu_2770_p52;
reg  signed [15:0] a_V_reg_3165;
reg  signed [9:0] w_V_reg_3170;
wire   [31:0] in_index_fu_2881_p3;
reg   [0:0] ap_phi_mux_do_init_phi_fu_527_p6;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_in_index22_phi_fu_1192_p6;
reg   [8:0] ap_phi_mux_w_index21_phi_fu_1206_p6;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read50_phi_reg_1216;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read151_phi_reg_1229;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read252_phi_reg_1242;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read353_phi_reg_1255;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read454_phi_reg_1268;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read555_phi_reg_1281;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read656_phi_reg_1294;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read757_phi_reg_1307;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read858_phi_reg_1320;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read959_phi_reg_1333;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1060_phi_reg_1346;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1161_phi_reg_1359;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1262_phi_reg_1372;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1363_phi_reg_1385;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1464_phi_reg_1398;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1565_phi_reg_1411;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1666_phi_reg_1424;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1767_phi_reg_1437;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1868_phi_reg_1450;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read1969_phi_reg_1463;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2070_phi_reg_1476;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2171_phi_reg_1489;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2272_phi_reg_1502;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2373_phi_reg_1515;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2474_phi_reg_1528;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2575_phi_reg_1541;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2676_phi_reg_1554;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2777_phi_reg_1567;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2878_phi_reg_1580;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read2979_phi_reg_1593;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3080_phi_reg_1606;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3181_phi_reg_1619;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3282_phi_reg_1632;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3383_phi_reg_1645;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3484_phi_reg_1658;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3585_phi_reg_1671;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3686_phi_reg_1684;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3787_phi_reg_1697;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3888_phi_reg_1710;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read3989_phi_reg_1723;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4090_phi_reg_1736;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4191_phi_reg_1749;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4292_phi_reg_1762;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4393_phi_reg_1775;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4494_phi_reg_1788;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4595_phi_reg_1801;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4696_phi_reg_1814;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4797_phi_reg_1827;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4898_phi_reg_1840;
wire   [15:0] ap_phi_reg_pp0_iter0_p_read4999_phi_reg_1853;
reg   [15:0] ap_phi_mux_acc_V20_phi_fu_1870_p6;
reg    ap_loop_init_pp0_iter1_reg;
reg    ap_loop_init_pp0_iter2_reg;
reg    ap_loop_init_pp0_iter3_reg;
reg    ap_loop_init_pp0_iter4_reg;
reg    ap_loop_init_pp0_iter5_reg;
reg   [15:0] ap_phi_mux_acc_V_phi_fu_2714_p20;
reg   [15:0] ap_phi_mux_acc_V_118_phi_fu_1884_p6;
reg   [15:0] ap_phi_mux_acc_V_21_phi_fu_2678_p20;
reg   [15:0] ap_phi_mux_acc_V_216_phi_fu_1898_p6;
reg   [15:0] ap_phi_mux_acc_V_22_phi_fu_2642_p20;
reg   [15:0] ap_phi_mux_acc_V_314_phi_fu_1912_p6;
reg   [15:0] ap_phi_mux_acc_V_23_phi_fu_2606_p20;
reg   [15:0] ap_phi_mux_acc_V_412_phi_fu_1926_p6;
reg   [15:0] ap_phi_mux_acc_V_24_phi_fu_2570_p20;
reg   [15:0] ap_phi_mux_acc_V_510_phi_fu_1940_p6;
reg   [15:0] ap_phi_mux_acc_V_25_phi_fu_2534_p20;
reg   [15:0] ap_phi_mux_acc_V_68_phi_fu_1954_p6;
reg   [15:0] ap_phi_mux_acc_V_26_phi_fu_2498_p20;
reg   [15:0] ap_phi_mux_acc_V_76_phi_fu_1968_p6;
reg   [15:0] ap_phi_mux_acc_V_27_phi_fu_2462_p20;
reg   [15:0] ap_phi_mux_acc_V_84_phi_fu_1982_p6;
reg   [15:0] ap_phi_mux_acc_V_28_phi_fu_2426_p20;
reg   [15:0] ap_phi_mux_acc_V_92_phi_fu_1996_p6;
reg   [15:0] ap_phi_mux_acc_V_29_phi_fu_2390_p20;
reg   [15:0] ap_phi_mux_acc_V_19_phi_fu_2009_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_19_reg_2006;
wire   [0:0] icmp_ln1466_fu_2942_p2;
reg   [15:0] ap_phi_mux_acc_V_18_phi_fu_2047_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_18_reg_2044;
reg   [15:0] ap_phi_mux_acc_V_17_phi_fu_2085_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_17_reg_2082;
reg   [15:0] ap_phi_mux_acc_V_16_phi_fu_2123_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_16_reg_2120;
reg   [15:0] ap_phi_mux_acc_V_15_phi_fu_2161_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_15_reg_2158;
reg   [15:0] ap_phi_mux_acc_V_14_phi_fu_2199_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_14_reg_2196;
reg   [15:0] ap_phi_mux_acc_V_13_phi_fu_2237_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_13_reg_2234;
reg   [15:0] ap_phi_mux_acc_V_12_phi_fu_2275_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_12_reg_2272;
reg   [15:0] ap_phi_mux_acc_V_11_phi_fu_2313_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_11_reg_2310;
reg   [15:0] ap_phi_mux_acc_V_10_phi_fu_2351_p22;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_10_reg_2348;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_29_reg_2386;
wire   [15:0] acc_V_20_fu_2948_p2;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_28_reg_2422;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_27_reg_2458;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_26_reg_2494;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_25_reg_2530;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_24_reg_2566;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_23_reg_2602;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_22_reg_2638;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_21_reg_2674;
wire   [15:0] ap_phi_reg_pp0_iter5_acc_V_reg_2710;
wire   [63:0] zext_ln151_fu_2746_p1;
wire   [0:0] icmp_ln168_fu_2876_p2;
wire  signed [21:0] grp_fu_3128_p2;
wire  signed [15:0] lhs_fu_2903_p12;
wire  signed [15:0] rhs_fu_2894_p4;
wire  signed [16:0] sext_ln859_fu_2928_p1;
wire  signed [16:0] sext_ln859_7_fu_2932_p1;
wire   [16:0] sub_ln1466_fu_2936_p2;
reg    grp_fu_3128_ce;
reg   [13:0] ap_return_0_preg;
reg   [13:0] ap_return_1_preg;
reg   [13:0] ap_return_2_preg;
reg   [13:0] ap_return_3_preg;
reg   [13:0] ap_return_4_preg;
reg   [13:0] ap_return_5_preg;
reg   [13:0] ap_return_6_preg;
reg   [13:0] ap_return_7_preg;
reg   [13:0] ap_return_8_preg;
reg   [13:0] ap_return_9_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_422;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_return_0_preg = 14'd0;
#0 ap_return_1_preg = 14'd0;
#0 ap_return_2_preg = 14'd0;
#0 ap_return_3_preg = 14'd0;
#0 ap_return_4_preg = 14'd0;
#0 ap_return_5_preg = 14'd0;
#0 ap_return_6_preg = 14'd0;
#0 ap_return_7_preg = 14'd0;
#0 ap_return_8_preg = 14'd0;
#0 ap_return_9_preg = 14'd0;
end

myproject_dense_resource_ap_fixed_ap_fixed_16_8_5_3_0_config5_s_outdEe #(
    .DataWidth( 4 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

myproject_dense_resource_ap_fixed_ap_fixed_16_8_5_3_0_config5_s_w5_eOg #(
    .DataWidth( 10 ),
    .AddressRange( 500 ),
    .AddressWidth( 9 ))
w5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w5_V_address0),
    .ce0(w5_V_ce0),
    .q0(w5_V_q0)
);

myproject_mux_5032_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 32 ),
    .dout_WIDTH( 16 ))
mux_5032_16_1_1_U60(
    .din0(p_read50_phi_reg_1216),
    .din1(p_read151_phi_reg_1229),
    .din2(p_read252_phi_reg_1242),
    .din3(p_read353_phi_reg_1255),
    .din4(p_read454_phi_reg_1268),
    .din5(p_read555_phi_reg_1281),
    .din6(p_read656_phi_reg_1294),
    .din7(p_read757_phi_reg_1307),
    .din8(p_read858_phi_reg_1320),
    .din9(p_read959_phi_reg_1333),
    .din10(p_read1060_phi_reg_1346),
    .din11(p_read1161_phi_reg_1359),
    .din12(p_read1262_phi_reg_1372),
    .din13(p_read1363_phi_reg_1385),
    .din14(p_read1464_phi_reg_1398),
    .din15(p_read1565_phi_reg_1411),
    .din16(p_read1666_phi_reg_1424),
    .din17(p_read1767_phi_reg_1437),
    .din18(p_read1868_phi_reg_1450),
    .din19(p_read1969_phi_reg_1463),
    .din20(p_read2070_phi_reg_1476),
    .din21(p_read2171_phi_reg_1489),
    .din22(p_read2272_phi_reg_1502),
    .din23(p_read2373_phi_reg_1515),
    .din24(p_read2474_phi_reg_1528),
    .din25(p_read2575_phi_reg_1541),
    .din26(p_read2676_phi_reg_1554),
    .din27(p_read2777_phi_reg_1567),
    .din28(p_read2878_phi_reg_1580),
    .din29(p_read2979_phi_reg_1593),
    .din30(p_read3080_phi_reg_1606),
    .din31(p_read3181_phi_reg_1619),
    .din32(p_read3282_phi_reg_1632),
    .din33(p_read3383_phi_reg_1645),
    .din34(p_read3484_phi_reg_1658),
    .din35(p_read3585_phi_reg_1671),
    .din36(p_read3686_phi_reg_1684),
    .din37(p_read3787_phi_reg_1697),
    .din38(p_read3888_phi_reg_1710),
    .din39(p_read3989_phi_reg_1723),
    .din40(p_read4090_phi_reg_1736),
    .din41(p_read4191_phi_reg_1749),
    .din42(p_read4292_phi_reg_1762),
    .din43(p_read4393_phi_reg_1775),
    .din44(p_read4494_phi_reg_1788),
    .din45(p_read4595_phi_reg_1801),
    .din46(p_read4696_phi_reg_1814),
    .din47(p_read4797_phi_reg_1827),
    .din48(p_read4898_phi_reg_1840),
    .din49(p_read4999_phi_reg_1853),
    .din50(in_index22_reg_1189),
    .dout(a_V_fu_2770_p52)
);

myproject_mux_104_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_104_16_1_1_U61(
    .din0(ap_phi_mux_acc_V20_phi_fu_1870_p6),
    .din1(ap_phi_mux_acc_V_118_phi_fu_1884_p6),
    .din2(ap_phi_mux_acc_V_216_phi_fu_1898_p6),
    .din3(ap_phi_mux_acc_V_314_phi_fu_1912_p6),
    .din4(ap_phi_mux_acc_V_412_phi_fu_1926_p6),
    .din5(ap_phi_mux_acc_V_510_phi_fu_1940_p6),
    .din6(ap_phi_mux_acc_V_68_phi_fu_1954_p6),
    .din7(ap_phi_mux_acc_V_76_phi_fu_1968_p6),
    .din8(ap_phi_mux_acc_V_84_phi_fu_1982_p6),
    .din9(ap_phi_mux_acc_V_92_phi_fu_1996_p6),
    .din10(out_index_reg_3160_pp0_iter4_reg),
    .dout(lhs_fu_2903_p12)
);

myproject_mul_mul_16s_10s_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 22 ))
mul_mul_16s_10s_22_4_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_V_reg_3165),
    .din1(w_V_reg_3170),
    .ce(grp_fu_3128_ce),
    .dout(grp_fu_3128_p2)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_0_preg <= {{ap_phi_mux_acc_V_phi_fu_2714_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_1_preg <= {{ap_phi_mux_acc_V_21_phi_fu_2678_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_2_preg <= {{ap_phi_mux_acc_V_22_phi_fu_2642_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_3_preg <= {{ap_phi_mux_acc_V_23_phi_fu_2606_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_4_preg <= {{ap_phi_mux_acc_V_24_phi_fu_2570_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_5_preg <= {{ap_phi_mux_acc_V_25_phi_fu_2534_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_6_preg <= {{ap_phi_mux_acc_V_26_phi_fu_2498_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_7_preg <= {{ap_phi_mux_acc_V_27_phi_fu_2462_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_8_preg <= {{ap_phi_mux_acc_V_28_phi_fu_2426_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
            ap_return_9_preg <= {{ap_phi_mux_acc_V_29_phi_fu_2390_p20[15:2]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V20_reg_1866 <= 16'd65500;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V20_reg_1866 <= ap_phi_mux_acc_V_phi_fu_2714_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_118_reg_1880 <= 16'd65464;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_118_reg_1880 <= ap_phi_mux_acc_V_21_phi_fu_2678_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_216_reg_1894 <= 16'd65416;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_216_reg_1894 <= ap_phi_mux_acc_V_22_phi_fu_2642_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_314_reg_1908 <= 16'd65392;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_314_reg_1908 <= ap_phi_mux_acc_V_23_phi_fu_2606_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_412_reg_1922 <= 16'd164;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_412_reg_1922 <= ap_phi_mux_acc_V_24_phi_fu_2570_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_510_reg_1936 <= 16'd65340;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_510_reg_1936 <= ap_phi_mux_acc_V_25_phi_fu_2534_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_68_reg_1950 <= 16'd24;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_68_reg_1950 <= ap_phi_mux_acc_V_26_phi_fu_2498_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_76_reg_1964 <= 16'd65240;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_76_reg_1964 <= ap_phi_mux_acc_V_27_phi_fu_2462_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_84_reg_1978 <= 16'd476;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_84_reg_1978 <= ap_phi_mux_acc_V_28_phi_fu_2426_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1)) begin
            acc_V_92_reg_1992 <= 16'd116;
        end else if ((icmp_ln151_reg_3156_pp0_iter4_reg == 1'd0)) begin
            acc_V_92_reg_1992 <= ap_phi_mux_acc_V_29_phi_fu_2390_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_524 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        do_init_reg_524 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index22_reg_1189 <= in_index_fu_2881_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_index22_reg_1189 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1060_phi_reg_1346 <= p_read1060_phi_reg_1346;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1060_phi_reg_1346 <= p_read10;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1060_phi_reg_1346 <= ap_phi_reg_pp0_iter0_p_read1060_phi_reg_1346;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1161_phi_reg_1359 <= p_read1161_phi_reg_1359;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1161_phi_reg_1359 <= p_read11;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1161_phi_reg_1359 <= ap_phi_reg_pp0_iter0_p_read1161_phi_reg_1359;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1262_phi_reg_1372 <= p_read1262_phi_reg_1372;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1262_phi_reg_1372 <= p_read12;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1262_phi_reg_1372 <= ap_phi_reg_pp0_iter0_p_read1262_phi_reg_1372;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1363_phi_reg_1385 <= p_read1363_phi_reg_1385;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1363_phi_reg_1385 <= p_read13;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1363_phi_reg_1385 <= ap_phi_reg_pp0_iter0_p_read1363_phi_reg_1385;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1464_phi_reg_1398 <= p_read1464_phi_reg_1398;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1464_phi_reg_1398 <= p_read14;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1464_phi_reg_1398 <= ap_phi_reg_pp0_iter0_p_read1464_phi_reg_1398;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read151_phi_reg_1229 <= p_read151_phi_reg_1229;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read151_phi_reg_1229 <= p_read1;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read151_phi_reg_1229 <= ap_phi_reg_pp0_iter0_p_read151_phi_reg_1229;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1565_phi_reg_1411 <= p_read1565_phi_reg_1411;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1565_phi_reg_1411 <= p_read15;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1565_phi_reg_1411 <= ap_phi_reg_pp0_iter0_p_read1565_phi_reg_1411;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1666_phi_reg_1424 <= p_read1666_phi_reg_1424;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1666_phi_reg_1424 <= p_read16;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1666_phi_reg_1424 <= ap_phi_reg_pp0_iter0_p_read1666_phi_reg_1424;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1767_phi_reg_1437 <= p_read1767_phi_reg_1437;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1767_phi_reg_1437 <= p_read17;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1767_phi_reg_1437 <= ap_phi_reg_pp0_iter0_p_read1767_phi_reg_1437;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1868_phi_reg_1450 <= p_read1868_phi_reg_1450;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1868_phi_reg_1450 <= p_read18;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1868_phi_reg_1450 <= ap_phi_reg_pp0_iter0_p_read1868_phi_reg_1450;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read1969_phi_reg_1463 <= p_read1969_phi_reg_1463;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read1969_phi_reg_1463 <= p_read19;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read1969_phi_reg_1463 <= ap_phi_reg_pp0_iter0_p_read1969_phi_reg_1463;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2070_phi_reg_1476 <= p_read2070_phi_reg_1476;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2070_phi_reg_1476 <= p_read20;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2070_phi_reg_1476 <= ap_phi_reg_pp0_iter0_p_read2070_phi_reg_1476;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2171_phi_reg_1489 <= p_read2171_phi_reg_1489;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2171_phi_reg_1489 <= p_read21;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2171_phi_reg_1489 <= ap_phi_reg_pp0_iter0_p_read2171_phi_reg_1489;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2272_phi_reg_1502 <= p_read2272_phi_reg_1502;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2272_phi_reg_1502 <= p_read22;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2272_phi_reg_1502 <= ap_phi_reg_pp0_iter0_p_read2272_phi_reg_1502;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2373_phi_reg_1515 <= p_read2373_phi_reg_1515;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2373_phi_reg_1515 <= p_read23;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2373_phi_reg_1515 <= ap_phi_reg_pp0_iter0_p_read2373_phi_reg_1515;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2474_phi_reg_1528 <= p_read2474_phi_reg_1528;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2474_phi_reg_1528 <= p_read24;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2474_phi_reg_1528 <= ap_phi_reg_pp0_iter0_p_read2474_phi_reg_1528;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read252_phi_reg_1242 <= p_read252_phi_reg_1242;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read252_phi_reg_1242 <= p_read2;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read252_phi_reg_1242 <= ap_phi_reg_pp0_iter0_p_read252_phi_reg_1242;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2575_phi_reg_1541 <= p_read2575_phi_reg_1541;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2575_phi_reg_1541 <= p_read25;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2575_phi_reg_1541 <= ap_phi_reg_pp0_iter0_p_read2575_phi_reg_1541;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2676_phi_reg_1554 <= p_read2676_phi_reg_1554;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2676_phi_reg_1554 <= p_read26;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2676_phi_reg_1554 <= ap_phi_reg_pp0_iter0_p_read2676_phi_reg_1554;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2777_phi_reg_1567 <= p_read2777_phi_reg_1567;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2777_phi_reg_1567 <= p_read27;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2777_phi_reg_1567 <= ap_phi_reg_pp0_iter0_p_read2777_phi_reg_1567;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2878_phi_reg_1580 <= p_read2878_phi_reg_1580;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2878_phi_reg_1580 <= p_read28;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2878_phi_reg_1580 <= ap_phi_reg_pp0_iter0_p_read2878_phi_reg_1580;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read2979_phi_reg_1593 <= p_read2979_phi_reg_1593;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read2979_phi_reg_1593 <= p_read29;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read2979_phi_reg_1593 <= ap_phi_reg_pp0_iter0_p_read2979_phi_reg_1593;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3080_phi_reg_1606 <= p_read3080_phi_reg_1606;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3080_phi_reg_1606 <= p_read30;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3080_phi_reg_1606 <= ap_phi_reg_pp0_iter0_p_read3080_phi_reg_1606;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3181_phi_reg_1619 <= p_read3181_phi_reg_1619;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3181_phi_reg_1619 <= p_read31;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3181_phi_reg_1619 <= ap_phi_reg_pp0_iter0_p_read3181_phi_reg_1619;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3282_phi_reg_1632 <= p_read3282_phi_reg_1632;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3282_phi_reg_1632 <= p_read32;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3282_phi_reg_1632 <= ap_phi_reg_pp0_iter0_p_read3282_phi_reg_1632;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3383_phi_reg_1645 <= p_read3383_phi_reg_1645;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3383_phi_reg_1645 <= p_read33;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3383_phi_reg_1645 <= ap_phi_reg_pp0_iter0_p_read3383_phi_reg_1645;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3484_phi_reg_1658 <= p_read3484_phi_reg_1658;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3484_phi_reg_1658 <= p_read34;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3484_phi_reg_1658 <= ap_phi_reg_pp0_iter0_p_read3484_phi_reg_1658;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read353_phi_reg_1255 <= p_read353_phi_reg_1255;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read353_phi_reg_1255 <= p_read3;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read353_phi_reg_1255 <= ap_phi_reg_pp0_iter0_p_read353_phi_reg_1255;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3585_phi_reg_1671 <= p_read3585_phi_reg_1671;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3585_phi_reg_1671 <= p_read35;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3585_phi_reg_1671 <= ap_phi_reg_pp0_iter0_p_read3585_phi_reg_1671;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3686_phi_reg_1684 <= p_read3686_phi_reg_1684;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3686_phi_reg_1684 <= p_read36;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3686_phi_reg_1684 <= ap_phi_reg_pp0_iter0_p_read3686_phi_reg_1684;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3787_phi_reg_1697 <= p_read3787_phi_reg_1697;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3787_phi_reg_1697 <= p_read37;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3787_phi_reg_1697 <= ap_phi_reg_pp0_iter0_p_read3787_phi_reg_1697;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3888_phi_reg_1710 <= p_read3888_phi_reg_1710;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3888_phi_reg_1710 <= p_read38;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3888_phi_reg_1710 <= ap_phi_reg_pp0_iter0_p_read3888_phi_reg_1710;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read3989_phi_reg_1723 <= p_read3989_phi_reg_1723;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read3989_phi_reg_1723 <= p_read39;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read3989_phi_reg_1723 <= ap_phi_reg_pp0_iter0_p_read3989_phi_reg_1723;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4090_phi_reg_1736 <= p_read4090_phi_reg_1736;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4090_phi_reg_1736 <= p_read40;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4090_phi_reg_1736 <= ap_phi_reg_pp0_iter0_p_read4090_phi_reg_1736;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4191_phi_reg_1749 <= p_read4191_phi_reg_1749;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4191_phi_reg_1749 <= p_read41;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4191_phi_reg_1749 <= ap_phi_reg_pp0_iter0_p_read4191_phi_reg_1749;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4292_phi_reg_1762 <= p_read4292_phi_reg_1762;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4292_phi_reg_1762 <= p_read42;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4292_phi_reg_1762 <= ap_phi_reg_pp0_iter0_p_read4292_phi_reg_1762;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4393_phi_reg_1775 <= p_read4393_phi_reg_1775;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4393_phi_reg_1775 <= p_read43;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4393_phi_reg_1775 <= ap_phi_reg_pp0_iter0_p_read4393_phi_reg_1775;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4494_phi_reg_1788 <= p_read4494_phi_reg_1788;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4494_phi_reg_1788 <= p_read44;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4494_phi_reg_1788 <= ap_phi_reg_pp0_iter0_p_read4494_phi_reg_1788;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read454_phi_reg_1268 <= p_read454_phi_reg_1268;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read454_phi_reg_1268 <= p_read4;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read454_phi_reg_1268 <= ap_phi_reg_pp0_iter0_p_read454_phi_reg_1268;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4595_phi_reg_1801 <= p_read4595_phi_reg_1801;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4595_phi_reg_1801 <= p_read45;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4595_phi_reg_1801 <= ap_phi_reg_pp0_iter0_p_read4595_phi_reg_1801;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4696_phi_reg_1814 <= p_read4696_phi_reg_1814;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4696_phi_reg_1814 <= p_read46;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4696_phi_reg_1814 <= ap_phi_reg_pp0_iter0_p_read4696_phi_reg_1814;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4797_phi_reg_1827 <= p_read4797_phi_reg_1827;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4797_phi_reg_1827 <= p_read47;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4797_phi_reg_1827 <= ap_phi_reg_pp0_iter0_p_read4797_phi_reg_1827;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4898_phi_reg_1840 <= p_read4898_phi_reg_1840;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4898_phi_reg_1840 <= p_read48;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4898_phi_reg_1840 <= ap_phi_reg_pp0_iter0_p_read4898_phi_reg_1840;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read4999_phi_reg_1853 <= p_read4999_phi_reg_1853;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read4999_phi_reg_1853 <= p_read49;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read4999_phi_reg_1853 <= ap_phi_reg_pp0_iter0_p_read4999_phi_reg_1853;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read50_phi_reg_1216 <= p_read50_phi_reg_1216;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read50_phi_reg_1216 <= p_read;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read50_phi_reg_1216 <= ap_phi_reg_pp0_iter0_p_read50_phi_reg_1216;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read555_phi_reg_1281 <= p_read555_phi_reg_1281;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read555_phi_reg_1281 <= p_read5;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read555_phi_reg_1281 <= ap_phi_reg_pp0_iter0_p_read555_phi_reg_1281;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read656_phi_reg_1294 <= p_read656_phi_reg_1294;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read656_phi_reg_1294 <= p_read6;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read656_phi_reg_1294 <= ap_phi_reg_pp0_iter0_p_read656_phi_reg_1294;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read757_phi_reg_1307 <= p_read757_phi_reg_1307;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read757_phi_reg_1307 <= p_read7;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read757_phi_reg_1307 <= ap_phi_reg_pp0_iter0_p_read757_phi_reg_1307;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read858_phi_reg_1320 <= p_read858_phi_reg_1320;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read858_phi_reg_1320 <= p_read8;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read858_phi_reg_1320 <= ap_phi_reg_pp0_iter0_p_read858_phi_reg_1320;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd0)) begin
            p_read959_phi_reg_1333 <= p_read959_phi_reg_1333;
        end else if ((ap_phi_mux_do_init_phi_fu_527_p6 == 1'd1)) begin
            p_read959_phi_reg_1333 <= p_read9;
        end else if (~(icmp_ln151_fu_2764_p2 == 1'd1)) begin
            p_read959_phi_reg_1333 <= ap_phi_reg_pp0_iter0_p_read959_phi_reg_1333;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index21_reg_1203 <= w_index_reg_3145;
    end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        w_index21_reg_1203 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_V_reg_3165 <= a_V_fu_2770_p52;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        ap_loop_init_pp0_iter2_reg <= ap_loop_init_pp0_iter1_reg;
        icmp_ln151_reg_3156 <= icmp_ln151_fu_2764_p2;
        icmp_ln151_reg_3156_pp0_iter1_reg <= icmp_ln151_reg_3156;
        in_index_1_reg_3150 <= in_index_1_fu_2758_p2;
        out_index_reg_3160 <= outidx_q0;
        w_V_reg_3170 <= w5_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_init_pp0_iter3_reg <= ap_loop_init_pp0_iter2_reg;
        ap_loop_init_pp0_iter4_reg <= ap_loop_init_pp0_iter3_reg;
        ap_loop_init_pp0_iter5_reg <= ap_loop_init_pp0_iter4_reg;
        icmp_ln151_reg_3156_pp0_iter2_reg <= icmp_ln151_reg_3156_pp0_iter1_reg;
        icmp_ln151_reg_3156_pp0_iter3_reg <= icmp_ln151_reg_3156_pp0_iter2_reg;
        icmp_ln151_reg_3156_pp0_iter4_reg <= icmp_ln151_reg_3156_pp0_iter3_reg;
        out_index_reg_3160_pp0_iter2_reg <= out_index_reg_3160;
        out_index_reg_3160_pp0_iter3_reg <= out_index_reg_3160_pp0_iter2_reg;
        out_index_reg_3160_pp0_iter4_reg <= out_index_reg_3160_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_3145 <= w_index_fu_2752_p2;
    end
end

always @ (*) begin
    if (((icmp_ln151_fu_2764_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V20_phi_fu_1870_p6 = 16'd65500;
    end else begin
        ap_phi_mux_acc_V20_phi_fu_1870_p6 = acc_V20_reg_1866;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0))) begin
        ap_phi_mux_acc_V_10_phi_fu_2351_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_10_phi_fu_2351_p22 = ap_phi_mux_acc_V20_phi_fu_1870_p6;
    end else begin
        ap_phi_mux_acc_V_10_phi_fu_2351_p22 = ap_phi_reg_pp0_iter5_acc_V_10_reg_2348;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_118_phi_fu_1884_p6 = 16'd65464;
    end else begin
        ap_phi_mux_acc_V_118_phi_fu_1884_p6 = acc_V_118_reg_1880;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1))) begin
        ap_phi_mux_acc_V_11_phi_fu_2313_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_11_phi_fu_2313_p22 = ap_phi_mux_acc_V_118_phi_fu_1884_p6;
    end else begin
        ap_phi_mux_acc_V_11_phi_fu_2313_p22 = ap_phi_reg_pp0_iter5_acc_V_11_reg_2310;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2))) begin
        ap_phi_mux_acc_V_12_phi_fu_2275_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_12_phi_fu_2275_p22 = ap_phi_mux_acc_V_216_phi_fu_1898_p6;
    end else begin
        ap_phi_mux_acc_V_12_phi_fu_2275_p22 = ap_phi_reg_pp0_iter5_acc_V_12_reg_2272;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3))) begin
        ap_phi_mux_acc_V_13_phi_fu_2237_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_13_phi_fu_2237_p22 = ap_phi_mux_acc_V_314_phi_fu_1912_p6;
    end else begin
        ap_phi_mux_acc_V_13_phi_fu_2237_p22 = ap_phi_reg_pp0_iter5_acc_V_13_reg_2234;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4))) begin
        ap_phi_mux_acc_V_14_phi_fu_2199_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_14_phi_fu_2199_p22 = ap_phi_mux_acc_V_412_phi_fu_1926_p6;
    end else begin
        ap_phi_mux_acc_V_14_phi_fu_2199_p22 = ap_phi_reg_pp0_iter5_acc_V_14_reg_2196;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5))) begin
        ap_phi_mux_acc_V_15_phi_fu_2161_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_15_phi_fu_2161_p22 = ap_phi_mux_acc_V_510_phi_fu_1940_p6;
    end else begin
        ap_phi_mux_acc_V_15_phi_fu_2161_p22 = ap_phi_reg_pp0_iter5_acc_V_15_reg_2158;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6))) begin
        ap_phi_mux_acc_V_16_phi_fu_2123_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_16_phi_fu_2123_p22 = ap_phi_mux_acc_V_68_phi_fu_1954_p6;
    end else begin
        ap_phi_mux_acc_V_16_phi_fu_2123_p22 = ap_phi_reg_pp0_iter5_acc_V_16_reg_2120;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7))) begin
        ap_phi_mux_acc_V_17_phi_fu_2085_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_17_phi_fu_2085_p22 = ap_phi_mux_acc_V_76_phi_fu_1968_p6;
    end else begin
        ap_phi_mux_acc_V_17_phi_fu_2085_p22 = ap_phi_reg_pp0_iter5_acc_V_17_reg_2082;
    end
end

always @ (*) begin
    if (((icmp_ln1466_fu_2942_p2 == 1'd0) | (~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)))) begin
        ap_phi_mux_acc_V_18_phi_fu_2047_p22 = ap_phi_mux_acc_V_84_phi_fu_1982_p6;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_18_phi_fu_2047_p22 = 16'd0;
    end else begin
        ap_phi_mux_acc_V_18_phi_fu_2047_p22 = ap_phi_reg_pp0_iter5_acc_V_18_reg_2044;
    end
end

always @ (*) begin
    if ((~(out_index_reg_3160_pp0_iter4_reg == 4'd0) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd1) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd2) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd3) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd4) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd5) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd6) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd7) & ~(out_index_reg_3160_pp0_iter4_reg == 4'd8) & (icmp_ln1466_fu_2942_p2 == 1'd1))) begin
        ap_phi_mux_acc_V_19_phi_fu_2009_p22 = 16'd0;
    end else if (((icmp_ln1466_fu_2942_p2 == 1'd0) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd0)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd1)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd2)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd3)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd4)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd5)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd6)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd7)) | ((icmp_ln1466_fu_2942_p2 == 1'd1) & (out_index_reg_3160_pp0_iter4_reg == 4'd8)))) begin
        ap_phi_mux_acc_V_19_phi_fu_2009_p22 = ap_phi_mux_acc_V_92_phi_fu_1996_p6;
    end else begin
        ap_phi_mux_acc_V_19_phi_fu_2009_p22 = ap_phi_reg_pp0_iter5_acc_V_19_reg_2006;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_216_phi_fu_1898_p6 = 16'd65416;
    end else begin
        ap_phi_mux_acc_V_216_phi_fu_1898_p6 = acc_V_216_reg_1894;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd1)) begin
        ap_phi_mux_acc_V_21_phi_fu_2678_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_21_phi_fu_2678_p20 = ap_phi_mux_acc_V_11_phi_fu_2313_p22;
    end else begin
        ap_phi_mux_acc_V_21_phi_fu_2678_p20 = ap_phi_reg_pp0_iter5_acc_V_21_reg_2674;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd2)) begin
        ap_phi_mux_acc_V_22_phi_fu_2642_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_22_phi_fu_2642_p20 = ap_phi_mux_acc_V_12_phi_fu_2275_p22;
    end else begin
        ap_phi_mux_acc_V_22_phi_fu_2642_p20 = ap_phi_reg_pp0_iter5_acc_V_22_reg_2638;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd3)) begin
        ap_phi_mux_acc_V_23_phi_fu_2606_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_23_phi_fu_2606_p20 = ap_phi_mux_acc_V_13_phi_fu_2237_p22;
    end else begin
        ap_phi_mux_acc_V_23_phi_fu_2606_p20 = ap_phi_reg_pp0_iter5_acc_V_23_reg_2602;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd4)) begin
        ap_phi_mux_acc_V_24_phi_fu_2570_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_24_phi_fu_2570_p20 = ap_phi_mux_acc_V_14_phi_fu_2199_p22;
    end else begin
        ap_phi_mux_acc_V_24_phi_fu_2570_p20 = ap_phi_reg_pp0_iter5_acc_V_24_reg_2566;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd5)) begin
        ap_phi_mux_acc_V_25_phi_fu_2534_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_25_phi_fu_2534_p20 = ap_phi_mux_acc_V_15_phi_fu_2161_p22;
    end else begin
        ap_phi_mux_acc_V_25_phi_fu_2534_p20 = ap_phi_reg_pp0_iter5_acc_V_25_reg_2530;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd6)) begin
        ap_phi_mux_acc_V_26_phi_fu_2498_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_26_phi_fu_2498_p20 = ap_phi_mux_acc_V_16_phi_fu_2123_p22;
    end else begin
        ap_phi_mux_acc_V_26_phi_fu_2498_p20 = ap_phi_reg_pp0_iter5_acc_V_26_reg_2494;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd7)) begin
        ap_phi_mux_acc_V_27_phi_fu_2462_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_27_phi_fu_2462_p20 = ap_phi_mux_acc_V_17_phi_fu_2085_p22;
    end else begin
        ap_phi_mux_acc_V_27_phi_fu_2462_p20 = ap_phi_reg_pp0_iter5_acc_V_27_reg_2458;
    end
end

always @ (*) begin
    if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7))) begin
        ap_phi_mux_acc_V_28_phi_fu_2426_p20 = ap_phi_mux_acc_V_18_phi_fu_2047_p22;
    end else if ((out_index_reg_3160_pp0_iter4_reg == 4'd8)) begin
        ap_phi_mux_acc_V_28_phi_fu_2426_p20 = acc_V_20_fu_2948_p2;
    end else begin
        ap_phi_mux_acc_V_28_phi_fu_2426_p20 = ap_phi_reg_pp0_iter5_acc_V_28_reg_2422;
    end
end

always @ (*) begin
    if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | ((out_index_reg_3160_pp0_iter4_reg == 4'd10) | ((out_index_reg_3160_pp0_iter4_reg == 4'd11) | ((out_index_reg_3160_pp0_iter4_reg == 4'd12) | ((out_index_reg_3160_pp0_iter4_reg == 4'd13) | ((out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15)))))))) begin
        ap_phi_mux_acc_V_29_phi_fu_2390_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd0) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_29_phi_fu_2390_p20 = ap_phi_mux_acc_V_19_phi_fu_2009_p22;
    end else begin
        ap_phi_mux_acc_V_29_phi_fu_2390_p20 = ap_phi_reg_pp0_iter5_acc_V_29_reg_2386;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_314_phi_fu_1912_p6 = 16'd65392;
    end else begin
        ap_phi_mux_acc_V_314_phi_fu_1912_p6 = acc_V_314_reg_1908;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_412_phi_fu_1926_p6 = 16'd164;
    end else begin
        ap_phi_mux_acc_V_412_phi_fu_1926_p6 = acc_V_412_reg_1922;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_510_phi_fu_1940_p6 = 16'd65340;
    end else begin
        ap_phi_mux_acc_V_510_phi_fu_1940_p6 = acc_V_510_reg_1936;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_68_phi_fu_1954_p6 = 16'd24;
    end else begin
        ap_phi_mux_acc_V_68_phi_fu_1954_p6 = acc_V_68_reg_1950;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_76_phi_fu_1968_p6 = 16'd65240;
    end else begin
        ap_phi_mux_acc_V_76_phi_fu_1968_p6 = acc_V_76_reg_1964;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_84_phi_fu_1982_p6 = 16'd476;
    end else begin
        ap_phi_mux_acc_V_84_phi_fu_1982_p6 = acc_V_84_reg_1978;
    end
end

always @ (*) begin
    if ((ap_loop_init_pp0_iter5_reg == 1'b1)) begin
        ap_phi_mux_acc_V_92_phi_fu_1996_p6 = 16'd116;
    end else begin
        ap_phi_mux_acc_V_92_phi_fu_1996_p6 = acc_V_92_reg_1992;
    end
end

always @ (*) begin
    if ((out_index_reg_3160_pp0_iter4_reg == 4'd0)) begin
        ap_phi_mux_acc_V_phi_fu_2714_p20 = acc_V_20_fu_2948_p2;
    end else if (((out_index_reg_3160_pp0_iter4_reg == 4'd9) | (out_index_reg_3160_pp0_iter4_reg == 4'd10) | (out_index_reg_3160_pp0_iter4_reg == 4'd11) | (out_index_reg_3160_pp0_iter4_reg == 4'd12) | (out_index_reg_3160_pp0_iter4_reg == 4'd13) | (out_index_reg_3160_pp0_iter4_reg == 4'd14) | (out_index_reg_3160_pp0_iter4_reg == 4'd15) | (out_index_reg_3160_pp0_iter4_reg == 4'd1) | (out_index_reg_3160_pp0_iter4_reg == 4'd2) | (out_index_reg_3160_pp0_iter4_reg == 4'd3) | (out_index_reg_3160_pp0_iter4_reg == 4'd4) | (out_index_reg_3160_pp0_iter4_reg == 4'd5) | (out_index_reg_3160_pp0_iter4_reg == 4'd6) | (out_index_reg_3160_pp0_iter4_reg == 4'd7) | (out_index_reg_3160_pp0_iter4_reg == 4'd8))) begin
        ap_phi_mux_acc_V_phi_fu_2714_p20 = ap_phi_mux_acc_V_10_phi_fu_2351_p22;
    end else begin
        ap_phi_mux_acc_V_phi_fu_2714_p20 = ap_phi_reg_pp0_iter5_acc_V_reg_2710;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_do_init_phi_fu_527_p6 = 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_do_init_phi_fu_527_p6 = 1'd1;
    end else begin
        ap_phi_mux_do_init_phi_fu_527_p6 = do_init_reg_524;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_in_index22_phi_fu_1192_p6 = in_index_fu_2881_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_in_index22_phi_fu_1192_p6 = 32'd0;
    end else begin
        ap_phi_mux_in_index22_phi_fu_1192_p6 = in_index22_reg_1189;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_w_index21_phi_fu_1206_p6 = w_index_reg_3145;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln151_reg_3156 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_mux_w_index21_phi_fu_1206_p6 = 9'd0;
    end else begin
        ap_phi_mux_w_index21_phi_fu_1206_p6 = w_index21_reg_1203;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_0 = {{ap_phi_mux_acc_V_phi_fu_2714_p20[15:2]}};
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_1 = {{ap_phi_mux_acc_V_21_phi_fu_2678_p20[15:2]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_2 = {{ap_phi_mux_acc_V_22_phi_fu_2642_p20[15:2]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_3 = {{ap_phi_mux_acc_V_23_phi_fu_2606_p20[15:2]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_4 = {{ap_phi_mux_acc_V_24_phi_fu_2570_p20[15:2]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_5 = {{ap_phi_mux_acc_V_25_phi_fu_2534_p20[15:2]}};
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_6 = {{ap_phi_mux_acc_V_26_phi_fu_2498_p20[15:2]}};
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_7 = {{ap_phi_mux_acc_V_27_phi_fu_2462_p20[15:2]}};
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_8 = {{ap_phi_mux_acc_V_28_phi_fu_2426_p20[15:2]}};
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln151_reg_3156_pp0_iter4_reg == 1'd1))) begin
        ap_return_9 = {{ap_phi_mux_acc_V_29_phi_fu_2390_p20[15:2]}};
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3128_ce = 1'b1;
    end else begin
        grp_fu_3128_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w5_V_ce0 = 1'b1;
    end else begin
        w5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_V_20_fu_2948_p2 = ($signed(rhs_fu_2894_p4) + $signed(lhs_fu_2903_p12));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_422 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_read1060_phi_reg_1346 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1161_phi_reg_1359 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1262_phi_reg_1372 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1363_phi_reg_1385 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1464_phi_reg_1398 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read151_phi_reg_1229 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1565_phi_reg_1411 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1666_phi_reg_1424 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1767_phi_reg_1437 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1868_phi_reg_1450 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read1969_phi_reg_1463 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2070_phi_reg_1476 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2171_phi_reg_1489 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2272_phi_reg_1502 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2373_phi_reg_1515 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2474_phi_reg_1528 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read252_phi_reg_1242 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2575_phi_reg_1541 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2676_phi_reg_1554 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2777_phi_reg_1567 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2878_phi_reg_1580 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read2979_phi_reg_1593 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3080_phi_reg_1606 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3181_phi_reg_1619 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3282_phi_reg_1632 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3383_phi_reg_1645 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3484_phi_reg_1658 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read353_phi_reg_1255 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3585_phi_reg_1671 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3686_phi_reg_1684 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3787_phi_reg_1697 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3888_phi_reg_1710 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read3989_phi_reg_1723 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4090_phi_reg_1736 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4191_phi_reg_1749 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4292_phi_reg_1762 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4393_phi_reg_1775 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4494_phi_reg_1788 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read454_phi_reg_1268 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4595_phi_reg_1801 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4696_phi_reg_1814 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4797_phi_reg_1827 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4898_phi_reg_1840 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read4999_phi_reg_1853 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read50_phi_reg_1216 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read555_phi_reg_1281 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read656_phi_reg_1294 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read757_phi_reg_1307 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read858_phi_reg_1320 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read959_phi_reg_1333 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_10_reg_2348 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_11_reg_2310 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_12_reg_2272 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_13_reg_2234 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_14_reg_2196 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_15_reg_2158 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_16_reg_2120 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_17_reg_2082 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_18_reg_2044 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_19_reg_2006 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_21_reg_2674 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_22_reg_2638 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_23_reg_2602 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_24_reg_2566 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_25_reg_2530 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_26_reg_2494 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_27_reg_2458 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_28_reg_2422 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_29_reg_2386 = 'bx;

assign ap_phi_reg_pp0_iter5_acc_V_reg_2710 = 'bx;

assign icmp_ln1466_fu_2942_p2 = ((sext_ln859_7_fu_2932_p1 == sub_ln1466_fu_2936_p2) ? 1'b1 : 1'b0);

assign icmp_ln151_fu_2764_p2 = ((ap_phi_mux_w_index21_phi_fu_1206_p6 == 9'd499) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_2876_p2 = (($signed(in_index_1_reg_3150) > $signed(32'd49)) ? 1'b1 : 1'b0);

assign in_index_1_fu_2758_p2 = (ap_phi_mux_in_index22_phi_fu_1192_p6 + 32'd1);

assign in_index_fu_2881_p3 = ((icmp_ln168_fu_2876_p2[0:0] == 1'b1) ? 32'd0 : in_index_1_reg_3150);

assign outidx_address0 = zext_ln151_fu_2746_p1;

assign rhs_fu_2894_p4 = {{grp_fu_3128_p2[21:6]}};

assign sext_ln859_7_fu_2932_p1 = rhs_fu_2894_p4;

assign sext_ln859_fu_2928_p1 = lhs_fu_2903_p12;

assign sub_ln1466_fu_2936_p2 = ($signed(17'd0) - $signed(sext_ln859_fu_2928_p1));

assign w5_V_address0 = zext_ln151_fu_2746_p1;

assign w_index_fu_2752_p2 = (ap_phi_mux_w_index21_phi_fu_1206_p6 + 9'd1);

assign zext_ln151_fu_2746_p1 = ap_phi_mux_w_index21_phi_fu_1206_p6;

endmodule //myproject_dense_resource_ap_fixed_ap_fixed_16_8_5_3_0_config5_s
