bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 132 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 20 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 15 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 10 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 25 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 6 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 11 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 11 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 3 -s 
bash scripts/getssimBR_cluster_random.sh map/map_cluster_random.csv 2 -s 
